name: deploy-todolist
on:
  push:
    branches:
      - main
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build app
        run: |
          npm run build
          mkdir package
          tar -czvf package/package.tar.gz dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: package/package.tar.gz
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ vars.AWS_HOST }}

      - name: Set up SSH
        run: |
          ssh-keyscan ${{ vars.AWS_HOST }} >> /home/runner/.ssh/known_hosts

      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          name: react-build
          path: ./package

      - name: "Debug: List contents of downloaded artifact directory"
        run: ls -lh ./package/

      - name: Deploy to server
        run: |
          scp ./package/package.tar.gz ${{ secrets.AWS_USER }}@${{ vars.AWS_HOST }}:/usr/local/repos/todolist-fe

      - name: Extract and move files
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ vars.AWS_HOST }} "/usr/local/repos/todolist-fe/deploy/deploy.sh"

        